name: When the pfocr_curation.rds file changes, update frontmatter fields

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - _data/pfocr_curation.rds

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:      
  stats-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          ref: main

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          sudo apt-get install libcurl4-openssl-dev libmagick++-dev
          Rscript -e 'install.packages("yaml")'

      - name: Update frontmatter
        run: |
          source("_rmd/updatefm.R")
          updateFrontmatter(c("figtitle","number","caption","organisms","year"), "pfocr_curation.rds")
        shell: Rscript {0} 
          
      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Update wpid fields in frontmatter'
              git pull --rebase
              git push
          fi
