name: When the wpid_map.tsv file changes, update wpid frontmatter fields

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - _data/wpid_map.tsv

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:      
  stats-update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: main

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          sudo apt-get install libcurl4-openssl-dev libmagick++-dev
          Rscript -e 'install.packages("yaml")'

      - name: Update frontmatter
        run: |
          Rscript -e "source('_rmd/updatefm.R')"
          Rscript -e "source('_rmd/updateFrontmatter("wpid", "wpid_map")')"

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Update wpid fields in frontmatter'
              git push
          fi
